### ISSUE TITLE
When color is turned on formatting gets messed up

### ISSUE THREAD

**Issue by hipstersmoothie** [ahmadnassri/node-pretty-exceptions#9]
### I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request

## Detailed Description

Italic gets turned on and messes up render.

Without Color it works fine:

![screen shot 2018-07-11 at 11 32 14 am](https://user-images.githubusercontent.com/1192452/42592449-697ae30c-84fe-11e8-8456-ed82f9fcbd9b.png)

But when I turn on color the formatting gets messed up and randomly turn my terminal text italic. It even effect output from other CLI utilites:

![screen shot 2018-07-11 at 11 35 43 am](https://user-images.githubusercontent.com/1192452/42592494-94197402-84fe-11e8-9663-ae80f7364e62.png)

### Expected Behavior

Text should not turn italic

### Current Behavior

Messed up fromatting

## Context

The lines look wonky!

### Your Environment

| software         | version
| ---------------- | -------
| package          | 1.4.0
| node             | 9.10.0
| npm              | 5.6.0
| Operating System | macOS 10.13.5

**Comment by ahmadnassri** [comment]
is this still occuring?
